

# Loading data

In [2]:
import pandas as pd

data = pd.read_csv('zad2_Airline.csv', sep=';', na_values='NA')
data.head()

,satisfaction,Gender,Customer.Type,Age,Type.of.Travel,Class,Flight.Distance,Seat.comfort,Departure.Arrival.time.convenient,Food.and.drink,...,Online.support,Ease.of.Online.booking,On.board.service,Leg.room.service,Baggage.handling,Checkin.service,Cleanliness,Online.boarding,Departure.Delay.in.Minutes,Arrival.Delay.in.Minutes
0,satisfied,Female,Loyal Customer,20.0,Personal Travel,Eco,3009,0,1,0,...,3,4,1,2,3,1,4,4,0,0.0
1,satisfied,Female,Loyal Customer,48.0,Personal Travel,Eco,1449,0,1,0,...,2,2,2,1,2,4,2,2,0,2.0
2,satisfied,Male,NaN,NaN,Personal Travel,Eco,2840,0,1,0,...,4,4,2,4,2,4,3,4,0,0.0
3,satisfied,Male,Loyal Customer,13.0,Personal Travel,Eco,2306,0,1,0,...,3,4,4,2,3,2,2,4,0,0.0
4,satisfied,Male,Loyal Customer,34.0,Personal Travel,Eco,1952,0,1,0,...,2,2,3,4,4,4,4,2,10,0.0

# Statistical description before eliminating missing data

In [3]:
data_stats_before = data.describe()
data_stats_before
# Selected columns for which we want to display statistics
selected_columns1 = ['Customer.Type', 'Age', 'Gate.location', 'Arrival.Delay.in.Minutes']

selected_data1 = data[selected_columns1]
print("Statistics of selected columns before eliminating missing values:")
print(selected_data1.describe())

Statistics of selected columns before eliminating missing values:
               Age  Gate.location  Arrival.Delay.in.Minutes
count  3914.000000    3900.000000               3985.000000
mean     39.327798       2.992564                 15.701129
std      15.150699       1.307228                 40.261585
min       7.000000       1.000000                  0.000000
25%      27.000000       2.000000                  0.000000
50%      39.000000       3.000000                  0.000000
75%      51.000000       4.000000                 14.000000
max      85.000000       5.000000                729.000000

# Variables that contain missing values

In [4]:
columns_with_na = data.columns[data.isna().any()].tolist()
print(columns_with_na)

['Customer.Type', 'Age', 'Gate.location', 'Arrival.Delay.in.Minutes']

# Filling the gaps among categorical variables

In [5]:
categorical_columns = ['Customer.Type', 'Type.of.Travel', 'Class','Gender']

for col in categorical_columns:
    most_common = data[col].mode()[0]
    data[col].fillna(most_common, inplace=True)
data.head()

,satisfaction,Gender,Customer.Type,Age,Type.of.Travel,Class,Flight.Distance,Seat.comfort,Departure.Arrival.time.convenient,Food.and.drink,...,Online.support,Ease.of.Online.booking,On.board.service,Leg.room.service,Baggage.handling,Checkin.service,Cleanliness,Online.boarding,Departure.Delay.in.Minutes,Arrival.Delay.in.Minutes
0,satisfied,Female,Loyal Customer,20.0,Personal Travel,Eco,3009,0,1,0,...,3,4,1,2,3,1,4,4,0,0.0
1,satisfied,Female,Loyal Customer,48.0,Personal Travel,Eco,1449,0,1,0,...,2,2,2,1,2,4,2,2,0,2.0
2,satisfied,Male,Loyal Customer,NaN,Personal Travel,Eco,2840,0,1,0,...,4,4,2,4,2,4,3,4,0,0.0
3,satisfied,Male,Loyal Customer,13.0,Personal Travel,Eco,2306,0,1,0,...,3,4,4,2,3,2,2,4,0,0.0
4,satisfied,Male,Loyal Customer,34.0,Personal Travel,Eco,1952,0,1,0,...,2,2,3,4,4,4,4,2,10,0.0

##Replacing categorical variables

In [6]:
data['satisfaction'] = data['satisfaction'].map({'satisfied': 1, 'dissatisfied': 0})
data['Gender'] = data['Gender'].map({'Male': 1, 'Female': 0})
data['Customer.Type'] = data['Customer.Type'].map({'Loyal Customer': 1, 'disloyal Customer': 0})
data['Type.of.Travel'] = data['Type.of.Travel'].map({'Personal Travel': 1, 'Business travel': 0})

categorical_columns = ['Class']
data_encoded = pd.get_dummies(data, columns=categorical_columns)
data = data_encoded.copy()
data_encoded.head()

,satisfaction,Gender,Customer.Type,Age,Type.of.Travel,Flight.Distance,Seat.comfort,Departure.Arrival.time.convenient,Food.and.drink,Gate.location,...,Leg.room.service,Baggage.handling,Checkin.service,Cleanliness,Online.boarding,Departure.Delay.in.Minutes,Arrival.Delay.in.Minutes,Class_Business,Class_Eco,Class_Eco Plus
0,1,0,1,20.0,1,3009,0,1,0,3.0,...,2,3,1,4,4,0,0.0,0,1,0
1,1,0,1,48.0,1,1449,0,1,0,3.0,...,1,2,4,2,2,0,2.0,0,1,0
2,1,1,1,NaN,1,2840,0,1,0,3.0,...,4,2,4,3,4,0,0.0,0,1,0
3,1,1,1,13.0,1,2306,0,1,0,3.0,...,2,3,2,2,4,0,0.0,0,1,0
4,1,1,1,34.0,1,1952,0,1,0,3.0,...,4,4,4,4,2,10,0.0,0,1,0

## Method 1: Deleting rows with missing values

In [7]:
data_dropped1 = data.dropna()
data_dropped1.describe()

selected_data2 = data_dropped1[selected_columns1]
print("Statistics of selected columns for the method of removing rows with missing data:")
print(selected_data2.describe())

Statistics of selected columns for the method of removing rows with missing data:
       Customer.Type          Age  Gate.location  Arrival.Delay.in.Minutes
count    3801.000000  3801.000000    3801.000000               3801.000000
mean        0.823731    39.322284       2.991318                 15.740858
std         0.381099    15.174235       1.306735                 40.584317
min         0.000000     7.000000       1.000000                  0.000000
25%         1.000000    27.000000       2.000000                  0.000000
50%         1.000000    39.000000       3.000000                  0.000000
75%         1.000000    51.000000       4.000000                 14.000000
max         1.000000    85.000000       5.000000                729.000000

## Method 2: Filling missing values with the average for each column

In [8]:
data_mean_filled = data.fillna(data.mean())
data_mean_filled.describe()

selected_data3 = data_mean_filled[selected_columns1]
print("Statistics of selected columns for the method of filling missing values with mean for each column:")
print(selected_data3.describe())

Statistics of selected columns for the method of filling missing values with mean for each column:
       Customer.Type          Age  Gate.location  Arrival.Delay.in.Minutes
count    4000.000000  4000.000000    4000.000000               4000.000000
mean        0.823000    39.327798       2.992564                 15.701129
std         0.381716    14.986903       1.290780                 40.186005
min         0.000000     7.000000       1.000000                  0.000000
25%         1.000000    27.000000       2.000000                  0.000000
50%         1.000000    39.327798       3.000000                  0.000000
75%         1.000000    51.000000       4.000000                 14.000000
max         1.000000    85.000000       5.000000                729.000000

# Method 3: Filling in the gaps with regression

In [9]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingRegressor

data = pd.read_csv('zad2_Airline.csv', sep=';', na_values='NA')

categorical_columns = ['Customer.Type', 'Type.of.Travel', 'Class', 'Gender']

for col in categorical_columns:
    most_common = data[col].mode()[0]
    data[col].fillna(most_common, inplace=True)

data['satisfaction'] = data['satisfaction'].map({'satisfied': 1, 'dissatisfied': 0})
data['Gender'] = data['Gender'].map({'Male': 1, 'Female': 0})
data['Customer.Type'] = data['Customer.Type'].map({'Loyal Customer': 1, 'disloyal Customer': 0})
data['Type.of.Travel'] = data['Type.of.Travel'].map({'Personal Travel': 1, 'Business travel': 0})

# Perform one-hot encoding for the 'Class' column
categorical_columns = ['Class']
data_encoded = pd.get_dummies(data, columns=categorical_columns)

data_filled = data_encoded.copy()

regressor = HistGradientBoostingRegressor()

columns_to_impute = ['Age', 'Gate.location', 'Arrival.Delay.in.Minutes']

for col in columns_to_impute:
    X = data_filled.drop(columns=col, axis=1)
    y = data_filled[col]

    data_with_na = data_filled[data_filled[col].isna()]
    data_without_na = data_filled[data_filled[col].notna()]

    regressor.fit(X.loc[data_without_na.index], y.loc[data_without_na.index])

    predicted_values = regressor.predict(X.loc[data_with_na.index])

    data_filled.loc[data_with_na.index, col] = predicted_values

selected_data = data_filled[columns_to_impute]
print("Statistics of selected columns after imputing missing values using regression:")
print(selected_data.describe())

/usr/local/lib/python3.10/dist-packages/sklearn/experimental/enable_hist_gradient_boosting.py:16: UserWarning: Since version 1.0, it is not needed to import enable_hist_gradient_boosting anymore. HistGradientBoostingClassifier and HistGradientBoostingRegressor are now stable and can be normally imported from sklearn.ensemble.
  warnings.warn(

Statistics of selected columns after imputing missing values using regression:
               Age  Gate.location  Arrival.Delay.in.Minutes
count  4000.000000    4000.000000               4000.000000
mean     39.292128       2.991292                 15.764698
std      15.052146       1.300303                 40.288198
min       7.000000       0.849179                  0.000000
25%      27.000000       2.000000                  0.000000
50%      39.000000       3.000000                  0.000000
75%      51.000000       4.000000                 14.000000
max      85.000000       5.075035                729.000000

# Method 4: Filling missing data using the knn method

In [10]:
import pandas as pd
from sklearn.impute import KNNImputer

data = pd.read_csv('zad2_Airline.csv', sep=';', na_values='NA')

categorical_columns = ['Customer.Type', 'Type.of.Travel', 'Class', 'Gender']

for col in categorical_columns:
    most_common = data[col].mode()[0]
    data[col].fillna(most_common, inplace=True)

data['satisfaction'] = data['satisfaction'].map({'satisfied': 1, 'dissatisfied': 0})
data['Gender'] = data['Gender'].map({'Male': 1, 'Female': 0})
data['Customer.Type'] = data['Customer.Type'].map({'Loyal Customer': 1, 'disloyal Customer': 0})
data['Type.of.Travel'] = data['Type.of.Travel'].map({'Personal Travel': 1, 'Business travel': 0})

categorical_columns = ['Class']
data_encoded = pd.get_dummies(data, columns=categorical_columns)

data = data_encoded.copy()

knn_imputer = KNNImputer(n_neighbors=5)

rows_with_na = data[data.isna().any(axis=1)].index

data_filledKNN = data.copy()

data_filledKNN.iloc[rows_with_na] = knn_imputer.fit_transform(data_filledKNN.iloc[rows_with_na])

data_filledKNN.describe()

#selected_columns1 = ['satisfaction', 'Gender', 'Age']
selected_data5 = data_filledKNN[selected_columns1]
print("Statistics of selected columns for KNN method:")
print(selected_data5.describe())

Statistics of selected columns for KNN method:
       Customer.Type         Age  Gate.location  Arrival.Delay.in.Minutes
count    4000.000000  4000.00000    4000.000000               4000.000000
mean        0.823000    39.32520       2.996250                 15.676900
std         0.381716    15.02368       1.293072                 40.192821
min         0.000000     7.00000       1.000000                  0.000000
25%         1.000000    27.00000       2.000000                  0.000000
50%         1.000000    39.00000       3.000000                  0.000000
75%         1.000000    51.00000       4.000000                 14.000000
max         1.000000    85.00000       5.000000                729.000000

In [11]:
selected_columns1 = ['Customer.Type', 'Age', 'Gate.location', 'Arrival.Delay.in.Minutes']

selected_data1 = data[selected_columns1]
selected_data2 = data_dropped1[selected_columns1]
selected_data3 = data_mean_filled[selected_columns1]
selected_data4 = data_filled[selected_columns1]
selected_data5 = data_filledKNN[selected_columns1]

data_frames = {
    "Before NaN Elimination": selected_data1,
    "KNN": selected_data5,
    "Regression": selected_data4,
    "Mean Imputation": selected_data3,
    "Drop NaNs": selected_data2
}

merged_data = pd.concat(data_frames, axis=1)

print("Statistics of selected columns for different methods:")
print(merged_data.describe())

Statistics of selected columns for different methods:
      Before NaN Elimination                             \
               Customer.Type          Age Gate.location
count            4000.000000  3914.000000   3900.000000
mean                0.823000    39.327798      2.992564
std                 0.381716    15.150699      1.307228
min                 0.000000     7.000000      1.000000
25%                 1.000000    27.000000      2.000000
50%                 1.000000    39.000000      3.000000
75%                 1.000000    51.000000      4.000000
max                 1.000000    85.000000      5.000000

                                         KNN                            \
      Arrival.Delay.in.Minutes Customer.Type         Age Gate.location
count              3985.000000   4000.000000  4000.00000   4000.000000
mean                 15.701129      0.823000    39.32520      2.996250
std                  40.261585      0.381716    15.02368      1.293072
min                   0.000000      0.000000     7.00000      1.000000
25%                   0.000000      1.000000    27.00000      2.000000
50%                   0.000000      1.000000    39.00000      3.000000
75%                  14.000000      1.000000    51.00000      4.000000
max                 729.000000      1.000000    85.00000      5.000000

                                  Regression                             \
      Arrival.Delay.in.Minutes Customer.Type          Age Gate.location
count              4000.000000   4000.000000  4000.000000   4000.000000
mean                 15.676900      0.823000    39.292128      2.991292
std                  40.192821      0.381716    15.052146      1.300303
min                   0.000000      0.000000     7.000000      0.849179
25%                   0.000000      1.000000    27.000000      2.000000
50%                   0.000000      1.000000    39.000000      3.000000
75%                  14.000000      1.000000    51.000000      4.000000
max                 729.000000      1.000000    85.000000      5.075035

                               Mean Imputation                             \
      Arrival.Delay.in.Minutes   Customer.Type          Age Gate.location
count              4000.000000     4000.000000  4000.000000   4000.000000
mean                 15.764698        0.823000    39.327798      2.992564
std                  40.288198        0.381716    14.986903      1.290780
min                   0.000000        0.000000     7.000000      1.000000
25%                   0.000000        1.000000    27.000000      2.000000
50%                   0.000000        1.000000    39.327798      3.000000
75%                  14.000000        1.000000    51.000000      4.000000
max                 729.000000        1.000000    85.000000      5.000000

                                   Drop NaNs                             \
      Arrival.Delay.in.Minutes Customer.Type          Age Gate.location
count              4000.000000   3801.000000  3801.000000   3801.000000
mean                 15.701129      0.823731    39.322284      2.991318
std                  40.186005      0.381099    15.174235      1.306735
min                   0.000000      0.000000     7.000000      1.000000
25%                   0.000000      1.000000    27.000000      2.000000
50%                   0.000000      1.000000    39.000000      3.000000
75%                  14.000000      1.000000    51.000000      4.000000
max                 729.000000      1.000000    85.000000      5.000000


      Arrival.Delay.in.Minutes
count              3801.000000
mean                 15.740858
std                  40.584317
min                   0.000000
25%                   0.000000
50%                   0.000000
75%                  14.000000
max                 729.000000

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Prepared datasets (data_dropped1, data_mean_filled, data_filled, data_filledKNN)
datasets = [data_dropped1, data_mean_filled, data_filled, data_filledKNN]
dataset_names = ["Drop NaNs", "Mean Imputation", "Regression Imputation", "KNN Imputation"]

# Function to train and evaluate the model
def evaluate_model(X_train, X_test, y_train, y_test):
    model = DecisionTreeClassifier(random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    return accuracy

# Results dictionary
results = {}

# Loop through datasets to train and evaluate the model
for dataset, name in zip(datasets, dataset_names):
    X = dataset[selected_columns1].drop(columns=["Customer.Type"])
    y = dataset["Customer.Type"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    accuracy = evaluate_model(X_train, X_test, y_train, y_test)
    results[name] = accuracy

# Display results
for name, accuracy in results.items():
    print(f"Model accuracy for dataset '{name}': {accuracy:.2f}")

Model accuracy for dataset 'Drop NaNs': 0.78
Model accuracy for dataset 'Mean Imputation': 0.75
Model accuracy for dataset 'Regression Imputation': 0.75
Model accuracy for dataset 'KNN Imputation': 0.76